Run `dconf update` on postinst and postrm
We don't generate the configuration dynamically like debian does,
so we need to do this to keep the dconf database updated.

However, this call to dconf update is an Endless-specific thing, but we
don't want to have the package installation failing in case this call
fails for any reason (e.g. non-existent /etc/dconf/db directory), so
make sure it does not bring the whole script down when it fails.

https://phabricator.endlessm.com/T16493
https://phabricator.endlessm.com/T16823

diff --git a/debian/gdm3.postinst b/debian/gdm3.postinst
--- a/debian/gdm3.postinst
+++ b/debian/gdm3.postinst
@@ -72,6 +72,12 @@ if [ -L /etc/pam.d/gdm-welcome ]; then
     rm -f /etc/pam.d/gdm-welcome
 fi
 
+if [ "$1" = configure ]; then
+  # Create gdm system dconf db, but don't make the package
+  # installation fail in case there's an error here, please.
+  dconf update || true
+fi
+
 #DEBHELPER#
 
 if [ -x /etc/init.d/gdm3 ]; then
