Rebase previous Endless-specific changes on top
Summary of changes included in this commit:

  * Bump GDM epoch and reference it from Breaks/Replaces (from commit f80db022)
  * Create empty /etc/dconf/db/gdm.d (from commit c14faad2)
  * Disable Wayland support, not needed for Endless (from commit 8b2a4779)
  * Disable running X server as user, using the new configure flag (from commit 6cd22376)
  * Don't convert old GSettings file to dconf settings (from commit 8cd1418a)
  * Don't install GDM upstream defaults into /usr/share/gdm/dconf (from commit 70ef096b)
  * Don't install the default.desktop file (from commit 39cd7751)
  * Don't rename ourselves to gdm3 (from commit d79bbc65)
  * Drop Debian init script, not needed for Endless (from commit 2c76388f)
  * Drop po-up directory (from commit 32aaf778)
  * Make gdm3 depend on ncurses-bin (from commit 7c706d50)
  * Package upstream defaults for the greeter into /usr/share/gdm (from commit fdc2d601)
  * Pass the right location of locale.conf to --with-lang-file (from commit b1edabfc)
  * Recommend adwaita-icon-theme (from commit 773708de)
  * Run `dconf update` on postinst and postrm (from commit c3050e82)

Dropped changes from previous versions:

  * Don't expect anything installed under /usr/share/gnome-session:
    - This is now needed, otherwise it will break the login screen.

https://phabricator.endlessm.com/T20786

diff --git a/debian/gdm3.postinst b/debian/gdm3.postinst
--- a/debian/gdm3.postinst
+++ b/debian/gdm3.postinst
@@ -58,12 +58,6 @@ if [ "$1" = configure ] && [ -d /etc/systemd/system/ ]; then
   fi
 fi
 
-ucf --debconf-ok --three-way /usr/share/gdm/greeter.dconf-defaults /etc/gdm3/greeter.dconf-defaults
-ucfr gdm3 /etc/gdm3/greeter.dconf-defaults
-
-# debconf hangs if gdm3 gets started below without this
-db_stop || true
-
 # Setup pulseaudio to run as user service
 UNIT=/usr/lib/systemd/user/pulseaudio.socket
 USERUNITDIR=/var/lib/gdm3/.config/systemd/user
@@ -76,6 +70,12 @@ chown -R Debian-gdm:Debian-gdm /var/lib/gdm3
 
 if [ -L /etc/pam.d/gdm-welcome ]; then
     rm -f /etc/pam.d/gdm-welcome
+fi
+
+if [ "$1" = configure ]; then
+  # Create gdm system dconf db, but don't make the package
+  # installation fail in case there's an error here, please.
+  dconf update || true
 fi
 
 #DEBHELPER#
diff --git a/debian/gdm3.postrm b/debian/gdm3.postrm
--- a/debian/gdm3.postrm
+++ b/debian/gdm3.postrm
@@ -37,6 +37,10 @@ if [ "$1" = "purge" ] ; then
                         delgroup --system Debian-gdm || echo "Could not remove Debian-gdm group."
                 fi
         fi
+
+        # Remote gdm system dconf db, but don't make the package
+        # installation fail in case there's an error here, please.
+        dconf update || true
 fi
 
 #DEBHELPER#
