Run `dconf update` on postinst and postrm
We don't generate the configuration dynamically like debian does,
so we need to do this to keep the dconf database updated.

However, this call to dconf update is an Endless-specific thing, but we
don't want to have the package installation failing in case this call
fails for any reason (e.g. non-existent /etc/dconf/db directory), so
make sure it does not bring the whole script down when it fails.

(Cherry picked after rebase to 3.34 from commit
146c8e21ede92d66212e986aad234f10671cca51)

https://phabricator.endlessm.com/T16493
https://phabricator.endlessm.com/T16823

diff --git a/debian/gdm3.postinst b/debian/gdm3.postinst
--- a/debian/gdm3.postinst
+++ b/debian/gdm3.postinst
@@ -60,6 +60,12 @@ fi
 
 chown -R Debian-gdm:Debian-gdm /var/lib/gdm3
 
+if [ "$1" = configure ]; then
+  # Create gdm system dconf db, but don't make the package
+  # installation fail in case there's an error here, please.
+  dconf update || true
+fi
+
 #DEBHELPER#
 
 if [ -x /etc/init.d/gdm3 ]; then
