Xsession: update from debian branch
Debian customizes this script, but does so by overwriting it with
another entire file from the debian packaging.
Since that is confusing and we have a git repo for gdm, apply the
customizations here.

[endlessm/eos-shell#5116]

diff --git a/data/Xsession.in b/data/Xsession.in
--- a/data/Xsession.in
+++ b/data/Xsession.in
@@ -3,6 +3,7 @@
 # This is SORT OF LIKE an X session, but not quite.  You get a command as the
 # first argument (it could be multiple words, so run it with "eval").  As a
 # special case, the command can be:
+#  failsafe - Run an xterm only
 #  default - Run the appropriate Xclients startup (see the code below)
 #  custom - Run ~/.xsession and if that's not available run 'default'
 #
@@ -18,12 +19,85 @@
 # be set from gdm.
 #
 # Also note that this is not run as a login shell, this is just executed.
-# This is why we source the profile files below.
 #
 # based on:
 # $XConsortium: Xsession /main/10 1995/12/18 18:21:28 gildea $
 
-command="$@"
+PROGNAME=Xsession
+
+message () {
+  # pretty-print messages of arbitrary length; use xmessage if it
+  # is available and $DISPLAY is set
+  MESSAGE="$PROGNAME: $*"
+  echo "$MESSAGE" | fold -s -w ${COLUMNS:-80} >&2
+  if [ -n "$DISPLAY" ]; then
+    if [ -n "$zenity" ]; then
+      "$zenity" --info --text "$MESSAGE"
+    elif [ -n "$xmessage" ]; then
+      echo "$MESSAGE" | fold -s -w ${COLUMNS:-80} | $xmessage -center -file -
+    fi
+  fi
+}
+
+message_nonl () {
+  # pretty-print messages of arbitrary length (no trailing newline); use
+  # xmessage if it is available and $DISPLAY is set
+  MESSAGE="$PROGNAME: $*"
+  echo -n "$MESSAGE" | fold -s -w ${COLUMNS:-80} >&2;
+  if [ -n "$DISPLAY" ]; then
+    if [ -n "$zenity" ]; then
+      "$zenity" --info --text "$MESSAGE"
+    elif [ -n "$xmessage" ]; then
+      echo -n "$MESSAGE" | fold -s -w ${COLUMNS:-80} | $xmessage -center -file -
+    fi
+  fi
+}
+
+errormsg () {
+  # exit script with error
+  message "$*"
+  exit 1
+}
+
+internal_errormsg () {
+  # exit script with error; essentially a "THIS SHOULD NEVER HAPPEN" message
+  # One big call to message() for the sake of xmessage; if we had two then
+  # the user would have dismissed the error we want reported before seeing the
+  # request to report it.
+  errormsg "$*" \
+           "Please report the installed version of the \"xfree86-common\"" \
+           "package and the complete text of this error message to" \
+           "<debian-x@lists.debian.org>."
+}
+
+run_parts () {
+  # until run-parts --noexec is implemented
+  if [ -z "$1" ]; then
+    internal_errormsg "run_parts() called without an argument."
+  fi
+  if [ ! -d "$1" ]; then
+    internal_errormsg "run_parts() called, but \"$1\" does not exist or is" \
+                      "not a directory."
+  fi
+  for F in $(/bin/ls $1); do
+    if expr "$F" : '[[:alnum:]_-]\+$' > /dev/null 2>&1; then
+      if [ -f "$1/$F" ]; then
+        echo "$1/$F"
+      fi
+    fi
+  done
+}
+# initialize variables for use by all session scripts
+
+OPTIONFILE=/etc/X11/Xsession.options
+
+SYSRESOURCES=/etc/X11/Xresources
+USRRESOURCES=$HOME/.Xresources
+
+SYSSESSIONDIR=/etc/X11/Xsession.d
+USERXSESSION=$HOME/.xsession
+USERXSESSIONRC=$HOME/.xsessionrc
+ALTUSERXSESSION=$HOME/.Xsession
 
 # this will go into the .xsession-errors along with all other echo's
 # good for debugging where things went wrong
@@ -36,109 +110,40 @@ test -f "$HOME/.profile" && . "$HOME/.profile"
 test -f /etc/xprofile && . /etc/xprofile
 test -f "$HOME/.xprofile" && . "$HOME/.xprofile"
 
-# Translation stuff
-if [ -x "@libexecdir@/gdmtranslate" ] ; then
-  gdmtranslate="@libexecdir@/gdmtranslate"
-else
-  gdmtranslate=
+zenity=`which zenity 2>/dev/null`
+xmessage=`which xmessage 2>/dev/null`
+
+command="$1"
+
+if [ -z "$command" ] ; then
+  command=failsafe
 fi
 
-# Note that this should only go to zenity dialogs which always expect utf8
-gettextfunc () {
-  if [ "x$gdmtranslate" != "x" ] ; then
-    "$gdmtranslate" --utf8 "$1"
+if [ x"$command" = xfailsafe ] ; then
+  if [ -n "$zenity" ] ; then
+    "$zenity" --info --text "This is the failsafe xterm session.  Windows now have focus only if you have your cursor above them.  To get out of this mode type 'exit' in the window in the upper left corner"
   else
-    echo "$1"
+    echo "$0: Starting the failsafe xterm session."
   fi
-}
-
-OLD_IFS=$IFS
-
-gdmwhich () {
-  COMMAND="$1"
-  OUTPUT=
-  IFS=:
-  for dir in $PATH
-  do
-    if test -x "$dir/$COMMAND" ; then
-      if test "x$OUTPUT" = "x" ; then
-        OUTPUT="$dir/$COMMAND"
-      fi
-    fi
-  done
-  IFS=$OLD_IFS 
-  echo "$OUTPUT"
-}
-
-zenity=`gdmwhich zenity`
-
-# Note: ~/.xsession-errors is now done in the daemon so that it
-# works for ALL sessions (except ones named 'Failsafe')
+  exec xterm -geometry 80x24+0+0
+fi
 
 # clean up after xbanner
-freetemp=`gdmwhich freetemp`
+freetemp=`which freetemp 2>/dev/null`
 if [ -n "$freetemp" ] ; then
-	"$freetemp"
+        "$freetemp"
 fi
 
-userresources="$HOME/.Xresources"
 usermodmap="$HOME/.Xmodmap"
 userxkbmap="$HOME/.Xkbmap"
-
-sysresources=/etc/X11/Xresources 
-sysmodmap=/etc/X11/Xmodmap 
-sysxkbmap=/etc/X11/Xkbmap
-
-rh6sysresources=/etc/X11/xinit/Xresources 
-rh6sysmodmap=/etc/X11/xinit/Xmodmap 
-
-# merge in defaults
-if [ -f "$rh6sysresources" ]; then
-    xrdb -nocpp -merge "$rh6sysresources"
-fi
-
-if [ -f "$sysresources" ]; then
-    xrdb -nocpp -merge "$sysresources"
-fi
-
-if [ -f "$userresources" ]; then
-    xrdb -nocpp -merge "$userresources"
-fi
-
-# merge in keymaps
-if [ -f "$sysxkbmap" ]; then
-    setxkbmap `cat "$sysxkbmap"`
-    XKB_IN_USE=yes
-fi
 
 if [ -f "$userxkbmap" ]; then
     setxkbmap `cat "$userxkbmap"`
     XKB_IN_USE=yes
 fi
 
-#
-# Eeek, this seems like too much magic here
-#
-if [ -z "$XKB_IN_USE" -a ! -L /etc/X11/X ]; then
-    if grep '^exec.*/Xsun' /etc/X11/X > /dev/null 2>&1 && [ -f /etc/X11/XF86Config ]; then
-       xkbsymbols=`sed -n -e 's/^[     ]*XkbSymbols[   ]*"\(.*\)".*$/\1/p' /etc/X11/XF86Config`
-       if [ -n "$xkbsymbols" ]; then
-           setxkbmap -symbols "$xkbsymbols"
-           XKB_IN_USE=yes
-       fi
-    fi
-fi
-
 # xkb and xmodmap don't play nice together
 if [ -z "$XKB_IN_USE" ]; then
-    if [ -f "$rh6sysmodmap" ]; then
-       xmodmap "$rh6sysmodmap"
-    fi
-
-    if [ -f "$sysmodmap" ]; then
-       xmodmap "$sysmodmap"
-    fi
-
     if [ -f "$usermodmap" ]; then
        xmodmap "$usermodmap"
     fi
@@ -146,68 +151,47 @@ fi
 
 unset XKB_IN_USE
 
-# Overwrite $LANG from /etc/profile (and friends) with the one picked in the
-# greeter
 if [ -n "$GDM_LANG" ]; then
-  LANG="$GDM_LANG"
-  export LANG
-fi
+    # Set the locale to that, it’s the language selected in GDM.
+    LANG="$GDM_LANG"
+    export LANG
 
-xhost +si:localuser:`id -un` || :
-
-# run all system xinitrc shell scripts.
-if [ -d /etc/X11/xinit/xinitrc.d ]; then
-    for i in /etc/X11/xinit/xinitrc.d/* ; do
-        if [ -x "$i" -a ! -d "$i" ]; then
-	    . "$i"
-        fi
-    done
-fi
-
-if [ "x$command" = "xcustom" ] ; then
-  if [ -x "$HOME/.xsession" ]; then
-    command="$HOME/.xsession"
-  else
-    echo "$0: Cannot find ~/.xsession will try the default session"
-    command="default"
-  fi
-fi
-
-if [ "x$command" = "xdefault" ] ; then
-  if [ -x "$HOME/.Xclients" ]; then
-    command="$HOME/.Xclients"
-  elif [ -x /etc/X11/xinit/Xclients ]; then
-    command="/etc/X11/xinit/Xclients"
-  elif [ -x /etc/X11/Xclients ]; then
-    command="/etc/X11/Xclients"
-  else
-    if [ -n "$zenity" ] ; then
-	disptext=`gettextfunc "System has no Xclients file, so starting a failsafe xterm session.  Windows will have focus only if the mouse pointer is above them.  To get out of this mode type 'exit' in the window."`
-      "$zenity" --info --text "$disptext"
-    else
-      echo "$0: Cannot find Xclients"
+    if [ -n "$LC_ALL" ] && [ "$LC_ALL" != "$LANG" ]; then
+        LC_ALL="$LANG"
     fi
-    exec xterm -geometry 80x24+0+0
-  fi
+
+    # if GDM_LANG isn't first in LANGUAGE, then unset it.
+    if [ -n "$LANGUAGE" ]; then
+        if echo "$LANGUAGE" | grep -q -- "^$GDM_LANG"; then
+           :
+        else
+           unset LANGUAGE
+        fi
+    fi
 fi
 
-# add ssh-agent if found
-sshagent="`gdmwhich ssh-agent`"
-if [ -n "$sshagent" ] && [ -x "$sshagent" ] && [ -z "$SSH_AUTH_SOCK" ]; then
-    command="$sshagent -- $command"
-elif [ -z "$sshagent" ] ; then
-    echo "$0: ssh-agent not found!"
+# The default Debian session runs xsession first, so we just do that for
+# "custom"
+if [ "x$command" = "xcustom" ] ; then
+  shift
+  set default $*
 fi
 
-echo "$0: Setup done, will execute: $command"
+# use run-parts to source every file in the session directory; we source
+# instead of executing so that the variables and functions defined above
+# are available to the scripts, and so that they can pass variables to each
+# other
+SESSIONFILES=$(run_parts $SYSSESSIONDIR)
+if [ -n "$SESSIONFILES" ]; then
+  for SESSIONFILE in $SESSIONFILES; do
+    . $SESSIONFILE
+  done
+fi
 
-eval exec $command
-
-echo "$0: Executing $command failed, will run xterm"
+echo "$0: Executing $command failed, will try to run x-terminal-emulator"
 
 if [ -n "$zenity" ] ; then
-	disptext=`gettextfunc "Failed to start the session, so starting a failsafe xterm session.  Windows will have focus only if the mouse pointer is above them.  To get out of this mode type 'exit' in the window."`
-	"$zenity" --info --text "$disptext"
+        "$zenity" --info --text "I could not start your session and so I have started the failsafe xterm session.  Windows now have focus only if you have your cursor above them.  To get out of this mode type 'exit' in the window in the upper left corner"
 fi
 
-exec xterm -geometry 80x24+0+0
+exec x-terminal-emulator -geometry 80x24+0+0
